adj1 = input('Enter an adjective: ')
noun1 = input('Enter a noun: ')
verb1 = input('Enter a past tense verb: ')
adv1 = input('Enter an adverb: ')
adj2 = input('Enter an adjective: ')
noun2 = input('Enter a noun: ')
noun3 = input('Enter a noun: ')
adj3 = input('Enter an adjective: ')
verb2 = input('Enter a verb: ')
adv2 = input('Enter an adverb: ')
verb3 = input('Enter a past tense verb: ')
adj4 = input('Enter an adjective: ')

print()
print('A Day at the Zoo!')
print()
print('Today I went to the zoo.')
print('I saw a(n) {} {} jumping up and down in its tree.'.format(adj1,noun1))
print('He {} {} through the large tunnel that led to its {} {}.'.format(verb1,adv1,adj2,noun2))
print('''I got some peanuts and passed them through the cage to
a gigantic gray {} towering above my head.'''.format(noun3))
print('Feeding that animal made me hungry.')
print('I went to get a {} scoop of ice cream.'.format(adj3))
print('It filled my stomach.')
print('Afterwards I had to {} {} to catch our bus.'.format(verb2,adv2))
print('When I got home I {} my mom for a {} day at the zoo.'.format(verb3,adj4))
