print('Welcome to Mr. Purdy\'s Adventure Game...play at your own risk!')
print('Press <enter> to continue...')
input()
print('You are in a wide open grassy field.  In the distance')
print('you see what looks like a house.  In the opposite direction')
print('there appears to be a dark cave.')
print('Do you want to:')
print('1. Go towards the house.')
print('2. Go towards the cave.')
choice = input('> ')

if choice == '1':
    print()
    print('As you approach the house, it starts to look less and')
    print('less like any house you have ever seen.  There appear')
    print('to be 2 different doors: a large one, and a small one.')
    print('Do you want to:')
    print('1. Try the large door.')
    print('2. Try the small door.')
    choice = input('> ')
    
    if choice == '1':
        print()
        print('You jiggle the large door\'s handle.  Immediately')
        print('the door is flung open and a humongous troll')
        print('appears.  He must be hungry, because he looks')
        print('VERY happy to see you.  The last thing you')
        print('remember is the troll licking his lips and hitting')
        print('you over the head with a large object.')
        print('****THE END****')
    elif choice == '2':
        print()
        print('Just as you reach for the small door\'s knob')
        print('the door flies open and a hobgoblin jumps')
        print('out from the house and begins attacking you.')
        print('The last thing you remember is the hobgoblin')
        print('talking with a troll (it must be his roommate)')
        print('about the great dinner they are going to have')
        print('tonight.')
        print('****THE END****')
    else:
        print()
        print('While you were trying to decide which door to')
        print('open, a bolt of lightning strikes the spot')
        print('you are standing in.  What are the odds?')
        print('****THE END****')

elif choice == '2':
    print()
    print('As you begin walking towards the cave, you hear')
    print('a large thunder clap and see some lightning back')
    print('in the direction of that house.  Up ahead, the')
    print('cave is looking more and more menacing. As')
    print('you reach the mouth of the cave, you hear a low')
    print('rumble coming from inside.')
    print('Do you want to:')
    print('1. Call out, "Is anyone home?"')
    print('2. Quietly sneak into the cave entrance.')
    choice = input('> ')

    if choice == '1':
        print()
        print('You shout loudly, "Hello? Is anyone there?"')
        print('All you hear is your echo calling back,')
        print('"Hello? Is someone there?"')
        print('"Wait a minute", you exclaim,  "that isn\'t my echo,')
        print('there is someone in the cave answering me!"')
        print('Do you want to:')
        print('1. Rush into the cave')
        print('2. Continue yelling into the cave')
        choice = input('> ')
        
        if choice == '1':
            print()
            print('In your hurry to get into the cave, you')
            print('fail to notice the large ogre waiting')
            print('just inside.  He appears to be holding')
            print('some kind of voice altering device.  That\'s')
            print('too bad...for you.  Ogres love the taste of human.')
            print('****THE END****')
        elif choice == '2':
            print()
            print('You yell into the cave, "Who is that?!"')
            print('To which you hear a response, "It\'s me,')
            print('your future husband!  Which is strange, ')
            print('because the voice definitely sounds like')
            print('a woman.  Realizing that it must be a')
            print('trap, you run away from the cave and live')
            print('happily ever after...albeit alone.')
            print('****THE END****')
        else:
            print()
            print('While you were trying to decide what to do,')
            print('another bolt of lightning strikes the spot')
            print('you are standing in.  You don\'t feel any')
            print('pain, but can\'t help thinking, "What are ')
            print('the odds?')
            print('****THE END****')

    elif choice == '2':
        print()
        print('You quietly approach the cave entrance and')
        print('peer inside.  You can just barely see a dark')
        print('figure huddled in the corner.  It looks like')
        print('they\'re asleep.  Suddenly, you hear "Here\'s')
        print('number, so call me maybe...')
        print('Oh no, it\'s your cell phone ringer!  Who')
        print('could be calling you at this hour?  The figure')
        print('jumps up, startled by the terrible music in its')
        print('home!  It looks angry and confused.')
        print('Just as you are deciding what to do, you are')
        print('attacked from behind by a MUCH LARGER figure')
        print('which you hadn\'t noticed.  That\'s too bad.')
        print('****THE END****')
    else:
        print()
        print('While you were trying to decide what to do,')
        print('another bolt of lightning strikes the spot')
        print('you are standing in.  You don\'t feel any')
        print('pain, but can\'t help thinking, "What are ')
        print('the odds?')
        print('****THE END****')

else:
    print()
    print('While you were trying to decide what to do,')
    print('a bolt of lightning strikes the spot')
    print('you are standing in.  You don\'t feel any')
    print('pain, but can\'t help thinking, "What are ')
    print('the odds?')
    print('****THE END****')




